/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Context {
  
}
export interface CommandMeta {
  name?: string
  version?: string
  description?: string
  hidden?: boolean
}
export interface CommandOption {
  
}
export interface Command {
  meta: CommandMeta
  options: Record<string, CommandOption>
  callback: (ctx: Context) => void
}
export declare function defineCommand(options: Command): Command
